services:
  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: nest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    volumes:
      - ./backend:/workdir
      - /workdir/node_modules
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /workdir
          ignore:
            - node_modules
            - .pnpm
        - action: rebuild
          path: ./backend/package.json

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
