services:
  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: nest
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    volumes:
      - /backend/node_modules
    develop:
      watch:
        - action: sync
          path: .
          target: /backend
          ignore:
            - node_modules
        - action: rebuild
          path: ./package.json

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
